apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-practice
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ps-fast
  capacity:
    storage: 50Gi
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: persistent-volume-1
