apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-test
spec:
  replicas: 4
  selector:
    matchLabels:
      app: service-test
      colour: green
  template:
    metadata:
      labels:
        app: service-test
        colour: green
    spec:
      containers:
      - image: nginx
        name: nginx
