apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: banana
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: banana
  policyTypes:
    - Ingress
    - Egress
  # egress:
  #   - to: 
  #       - ipBlock:
  #           cidr: 8.8.4.0/24
  # ingress:
  #   - from:
  #     - podSelector:
  #         matchLabels:
  #           app: apple
  #     ports:
  #       - port: 80
