apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
    - name: demo
      image: nginx
      volumeMounts:
      - name: config
        mountPath: "/config"
        readOnly: true
  volumes:
    # You set volumes at the Pod level, then mount them into containers inside that Pod
    - name: config
      configMap:
        # Provide the name of the ConfigMap you want to mount.
        name: game-demo
        items:
        - key: "player_initial_lives"
          path: "player_initial_lives"
