apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: mypvc
  containers:
    - name: container
      image: nginx
      volumeMounts:
        - mountPath: "/usr/share/nginx/bananas"
          name: storage
