apiVersion: v1
kind: Pod
metadata:
  name: custom-name
  labels:
    app.kubernetes.io/name: MyApp
  namespace: bananas
spec:
  containers:
  - name: myapp-container
    image: nginx
    command: 
    - sh
    - -c
    - echo Bananas
  initContainers:
  - name: init-myservice
    image: nginx
    command: ['sh', '-c', 'echo Chill Winston']
